language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

jobs:
  include:
    - stage: cargo release
      deploy:
        provider: cargo
        token: "$API_TOKEN"
        skip_cleanup: true
        on:
          tags: true
